const webdriverio = require('webdriverio');
const mocha = require('mocha');
const chai = require('chai');

var options = {
    host: "localhost",
    port: 9515,
    desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions: {
            binary: '/usr/local/bin/electron',
            args: ['app=./main.js']
        }
    }
};

var client = webdriverio.remote(options);
var assert = require('chai').assert;

describe('Electron App testing for Jibo:', function() {

    before(function (done) {
        // Initialize the Test Electron app:
        this.timeout(10000);
        client.init(done);
    });

    // This function clicks the button which was passed to it,
    // then checks the text box to determine whether the value
    // generated by the button click is a real number:
    client.testButton = function(button) {
        return this
            .click(button)
            .getValue('#sampleTextBox').then(function(text) {
                assert.isTrue(isFinite(text));
            })
    }

    it('Test Button A', function(done) { client.testButton('#ButtonA').call(done) });
    // This should pass, because clicking ButtonA invokes Math.random()

    it('Test Button B', function(done) { client.testButton('#ButtonB').call(done) });
    // This should fail, because clicking ButtonB outputs the string 'Hello World'

    after(function (done) {
        client.end(done);
    });
});
